---
title: "Tabset Row"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
theme: 
      version: 4
      bootswatch: minty
---

```{r setup, include=FALSE}
library(flexdashboard)
library(metathis)
library(readr)
library(lubridate)
library(shiny)
library(shinyWidgets)
library(jsonlite)
library(maptools)
library(ggplot2)
library(tidyr)
library(dplyr)
library(purrr)
library(leaflet)
library(plotly)
library(DT)
library(ggthemes)
library(viridis)
library(table1)
ipf_lifts <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-08/ipf_lifts.csv") %>% mutate(sex2 = if_else(sex == "F", "Female", "Male")) %>% 
filter(division != "NA")
```

```{r}
## COMMENTED OUT 
## UNNEEDED with reactive below

# ## Removing non-SBD competitors and creating total three variable
# 
# SBD_IPF <- ipf_lifts %>% 
#   filter(event == "SBD")
#   
# 
# lifts <- SBD_IPF %>%
#   rowwise() %>%
#   mutate(total_three = sum(c(best3squat_kg, best3bench_kg, best3deadlift_kg), na.rm = TRUE))
```

```{r sbdipf}
filt_lift <- reactive({
 filtered() %>% 
  filter(event == "SBD") %>%
  rowwise() %>%
  mutate(total_three = sum(c(best3squat_kg, best3bench_kg, best3deadlift_kg), na.rm = TRUE))
})

```
---
title: '`IPF Lifting Data`'
---


Column {.sidebar}
-----------------------------------------------------------------------

### International Powerlifting Federation Data 
    
blalalalalalalalalala
blalalalalalalalalala
blalalalalalalalalala
blalalalalalalalalala
blalalalalalalalalala
blalalalalalalalalala
blalalalalalalalalala
blalalalalalalalalala
blalalalalalalalalala
blalalalalalalalalala
blalalalalalalalalala


### Data Filtering

```{r overall filter, echo=FALSE }
#sex options
selectizeInput('division_select', 'Select Division:',
            choices = c("All", ipf_lifts$division %>% unique()), selected="All", multiple = T)

overall.subset <- reactive({
    if (input$division_select=="All") {
      ipf_lifts
    }else{
      ipf_lifts %>% filter(division == input$division_select)
    }
  })

#meet options

selectInput('meet_select', 'Select Meets:',
                choices = c("All", (ipf_lifts$meet_name) %>% unique()),
                selected =  "All", multiple = T )


 overall.subset2 <- reactive({
    if (input$meet_select== "All") {
    overall.subset()
    }else{
   overall.subset() %>% filter(meet_name == input$meet_select)
    }
  })


 filtered <- reactive({
   overall.subset2()
 })
 
```


Column {.tabset}
-------------------------------------

### Age and Weight Lifted

```{r}
#build plot  
   agesex_Plot <- reactive({
    p <-  filt_lift() %>% #filt_lift() makes this reactive to filtered data
      ggplot(aes(x = age, y = total_three)) + 
      geom_bar(stat = "identity") +
      coord_flip()
    ggplot_build(p)
  })

#render the new plot as it changes
  renderPlot({
    agesex_Plot()
  })
```   
 
### Sex and Weight Lifted
    
```{r}
#commented out for interactive options  
# sex_lifting <- lifts %>%
#   ggplot(aes(x = date, y = total_three, color = sex)) + 
#   labs(x = "Date", y = "Total 3 Lifts") +
#   geom_line() +
#   facet_wrap(~sex2)
# sex_lifting
# 
# ggplotly(sex_lifting)

 weightsex_Plot <- reactive({
  p2 <-  filt_lift()  %>%
  ggplot(aes(x = date, y = total_three, color = sex)) + 
  labs(x = "Date", y = "Total 3 Lifts") +
  geom_line() +
  facet_wrap(~sex2)
 ggplot_build(p2)
  })
  
renderPlot({
    weightsex_Plot()
  })  
```

### Table

#### Select Options
```{r interactive, echo=FALSE }
#sex options
selectInput('sex_select', 'Select sex:',
            choices = c("All", ipf_lifts$sex2 %>% unique()), selected="All", multiple = T )

dt.subset <- reactive({
    if (input$sex_select=="All") {
      filtered()
    }else{
      filtered() %>% filter(sex2 == input$sex_select)
    }
  })

#age options

selectInput('ageclass_select', 'Select Age Class:', 
                choices = c("All", (ipf_lifts$age_class) %>% unique()), 
                selected =  "All", multiple = T  )


 dt.subset2 <- reactive({
    if (input$ageclass_select== "All") {
    dt.subset()
    }else{
   dt.subset() %>% filter(age_class == input$ageclass_select)
    }
  })

# renderUI({
#     selectInput('weightclass_select', 'Select Weight Class:', 
#                 choices = c("All", (dt.subset2()$weight_class_kg ) %>% unique()), 
#                 selected =  "All" )
#   })

selectInput('weightclass_select', 'Select Weight Class:', 
                choices = c("All", (ipf_lifts$weight_class_kg ) %>% unique()), 
                selected =  "All", multiple = T )

 
   dt.subset3 <- reactive({
    if (input$weightclass_select=="All") {
      dt.subset2()
    }else{
      dt.subset2() %>% filter(weight_class_kg == input$weightclass_select)
    }
  })
```   
   
#### Data TAble    
```{r}     
   #render table 
  renderDT(dt.subset3())

```

#### Table Display

```{r}  
   # Create the actual downloadButton
h4("download data below")
   renderUI( {
  downloadBttn(outputId ="downloadData", label = "Download", size = "sm")
 
})

output$downloadData<-downloadHandler(
 filename =  paste0("weightlifting-", Sys.Date(), ".csv" ),
    content = function(file) {

      write.csv(dt.subset3(), file=file)
    },
  contentType="text/csv"
)

```


### View overall filtered table

```{r}
renderDT(filtered())
```

### Instagram Handle 
```{r}
# meta() %>%
#   meta_social(
#     title = "Powerlifting Instagram",
#     description = "Follow our lifting progress as we prepare for our meet",
#     url = "https://www.instagram.com/gradschool_lifts/",
#     image = "https://www.instagram.com/p/Ch7whRjO251/",
#     image_alt = "Cydney & Reagan flex for the 'Gram",
#     og_type = "social media",
#     og_author = c("Cydney Jardine", "Reagan Chiaverini"),
#     twitter_card_type = "app",
#     twitter_creator = "@gradschool_lifts"
#   )
```



