---
title: "Tabset Row"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns

---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(lubridate)
library(shiny)
library(jsonlite)
library(maptools)
library(ggplot2)
library(tidyr)
library(dplyr)
library(purrr)
library(leaflet)
library(plotly)
library(DT)
library(ggthemes)
library(viridis)
library(table1)
library(ggthemes)
ipf_lifts <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-08/ipf_lifts.csv") %>% mutate(sex2 = if_else(sex == "F", "Female", "Male"))
```

```{r}
## Removing non-SBD competitors and creating total three variable

SBD_IPF <- ipf_lifts %>% 
  filter(event == "SBD")
  

lifts <- SBD_IPF %>%
  rowwise() %>%
  mutate(total_three = sum(c(best3squat_kg, best3bench_kg, best3deadlift_kg), na.rm = TRUE))
```


Column {data-width=1000}
-------------------------------------
   
### Age and Sex Most Lifted Table

```{r interactive, echo=FALSE }
#sex options
selectInput('sex_select', 'Select sex:',
            choices = c("All", ipf_lifts$sex2 %>% unique()), selected="All")

dt.subset <- reactive({
    if (input$sex_select=="All") {
      ipf_lifts
    }else{
      ipf_lifts %>% filter(sex2 == input$sex_select)
    }
  })

#age options

selectInput('ageclass_select', 'Select Age Class:', 
                choices = c("All", (ipf_lifts$age_class) %>% unique()), 
                selected =  "All" )


 dt.subset2 <- reactive({
    if (input$ageclass_select== "All") {
    dt.subset()
    }else{
   dt.subset() %>% filter(age_class == input$ageclass_select)
    }
  })

renderUI({
    selectInput('weightclass_select', 'Select Weight Class:', 
                choices = c("All", (dt.subset2()$weight_class_kg ) %>% unique()), 
                selected =  "All" )
  })

   dt.subset3 <- reactive({
    if (input$weightclass_select=="All") {
      dt.subset2()
    }else{
      dt.subset2() %>% filter(weight_class_kg == input$weightclass_select)
    }
  })

renderDataTable(dt.subset3())
   
```

Column {data-width=1300}
-------------------------------------

### Age and Weight Lifted

```{r}
lifts %>% 
  ggplot(aes(x = age_class, total_three))
```   
 
### Sex and Weight Lifted
    
```{r}
sex_lifting <- lifts %>%
  ggplot(aes(x = date, y = total_three, color = sex)) + 
  labs(x = "Date", y = "Sum of Top Powerlifts") +
  geom_line() +
  facet_wrap(~sex2) +
  theme_tufte()


ggplotly(sex_lifting)
```
