---
title: "Project File"
output: html_document
date: '2022-11-16'
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
#### Packages ####
## If a package is installed, it will be loaded. If any 
## are not, the missing package(s) will be installed 
## from CRAN and then loaded.

## Packages of interest
packages = c("tidyverse", "flexdashboard", "shiny", "DT")

## Now load or install&load all
package.check <- lapply(
  packages,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
      library(x, character.only = TRUE)}})

```


```{r}
ipf_lifts <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-08/ipf_lifts.csv") %>% mutate(sex2 = if_else(sex == "F", "Female", "Male"))
```

## Removing non-SBD competitors and creating total three variable
```{r}

SBD_IPF <- ipf_lifts %>% 
  filter(event == "SBD")
  

lifts <- SBD_IPF %>%
  rowwise() %>%
  mutate(total_three = sum(c(best3squat_kg, best3bench_kg, best3deadlift_kg), na.rm = TRUE))

```


##GAMEPLAN: 1 pane = gender, 1 pane = interactive age groups, 1 pane = top scores, text-block

## EDA Set Up


```{r overall totals}
library(broom)
table_1 <- lifts %>%
  group_by(sex, age_class, weight_class_kg) %>%
  summarize(Total = n())

library(table1)
table_1 <- table1(lifts, ~ age_class, weight_class_kg | sex)

table_2 <- lifts %>%
  group_by(sex) %>%
  summarize(Total = n())
table_2 <- lifts %>%
  group_by(age_class) %>%
  summarize(Total = n())

```  





## PANE 2 INTERACTIVE


```{r interactive, echo=FALSE }
#sex options
selectInput('sex_select', 'Select sex:',
            choices = c("All", ipf_lifts$sex2 %>% unique()), selected="All")

dt.subset <- reactive({
    if (input$sex_select=="All") {
      ipf_lifts
    }else{
      ipf_lifts %>% filter(sex2 == input$sex_select)
    }
  })

#age options
 renderUI({
    selectInput('ageclass_select', 'Select Age Class:', 
                choices = c("All", (dt.subset()$age_class) %>% unique()), 
                selected =  "All" )
  })

 dt.subset2 <- reactive({
    if (input$ageclass_select=="All") {
      dt.subset()
    }else{
      dt.subset() %>% filter(age_class == input$ageclass_select)
    }
  })
 
 #weight class 
  renderUI({
    selectInput('weightclass_select', 'Select Weight Class:', 
                choices = c("All", (dt.subset2()$weight_class_kg ) %>% unique()), 
                selected =  "All" )
  })

   dt.subset3 <- reactive({
    if (input$weightclass_select=="All") {
      dt.subset2()
    }else{
      dt.subset2() %>% filter(weight_class_kg == input$weightclass_select)
    }
  })

renderDataTable(dt.subset3())

```


```{r interactive }
sex_options <- c("Male", "Female", "Both")
ageclass_options <- c(unique(ipf_lifts$age_class))
weightclass_options <- c(unique(ipf_lifts$weight_class_kg))
#add other options later

#ageclass_options <- reactive( c(unique(userFiltered()$age_class)) )
```

```{r user selection, echo=F}
selectInput("select_sex", label = "Select Gender:", choices = sex_options)
selectInput("select_ageclass", label = "Select Age Group:", choices = ageclass_options)
selectInput("select_weightclass", label = "Select Weight Group:", choices = weightclass_options)

```


```{r filter, include=F}
#first filter sex
userFiltered <- reactive(
  if(input$select_sex == "Both")
    {ipf_lifts}
  else{
    ipf_lifts %>% filter(sex2 == input$select_sex )
  })


#then filter age
userFiltered2 <- reactive(
  if(input$select_ageclass == "NA")
    {userFiltered()}
  else{
    userFiltered() %>% filter(age_class == input$select_ageclass)
  })
   
#then filter age
userFiltered3 <- reactive(
  if(input$select_weightclass == "NA")
    {userFiltered2()}
  else{
    userFiltered2() %>% filter(weight_class_kg == input$select_weightclass)
  })


# renderDataTable(userFiltered2())
```

```{r interactive info}
avg_data <- reactive({
userFiltered3() %>% summarise(
  mean_age = mean(age, na.rm = T),
  mean_deadlift = mean(best3deadlift_kg, na.rm = T)
  
) })

renderDataTable(avg_data())

```

## Setting up Sex and Weight Lifted Graph
```{r}

```

